name: Publish Python 🐍 distribution 📦 to PyPI and GitHub

on:
  push:
    tags:
      - "*"  # Only trigger on tag push (e.g., v0.1.0)

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install build tool
      run: python -m pip install build --user

    - name: Build a binary wheel and source tarball
      run: python -m build

    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: Publish to PyPI 📦
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/bayesreconpy  # ← your package on PyPI

    permissions:
      id-token: write  # Trusted publishing requirement

    steps:
    - name: Download distribution packages
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  github-release:
    name: Create GitHub Release and Sign Artifacts
    needs: publish-to-pypi
    runs-on: ubuntu-latest

    permissions:
      contents: write  # For GitHub release
      id-token: write  # For Sigstore signing

    steps:
    - name: Download distribution packages
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: Sign the distributions with Sigstore
      uses: sigstore/gh-action-sigstore-python@v3.0.0
      with:
        inputs: dist/*.tar.gz dist/*.whl

    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        gh release create "$GITHUB_REF_NAME" \
          --repo "$GITHUB_REPOSITORY" \
          --notes ""

    - name: Upload signed artifacts to GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        gh release upload "$GITHUB_REF_NAME" dist/** \
          --repo "$GITHUB_REPOSITORY"